"""init 8

Revision ID: 2a4fe10bc1c5
Revises: 262729f9eb79
Create Date: 2025-08-19 15:38:04.810716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4fe10bc1c5'
down_revision: Union[str, Sequence[str], None] = '262729f9eb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('numero_orden', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('sucursal_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordenes_detalle',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orden_id', sa.String(), nullable=False),
    sa.Column('producto_variante_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ),
    sa.ForeignKeyConstraint(['producto_variante_id'], ['producto_variantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordenes_detalle')
    op.drop_table('ordenes')
    # ### end Alembic commands ###
