"""init 6

Revision ID: 3e2351a86a60
Revises: 4dcc379ea8dc
Create Date: 2025-08-18 11:10:38.743999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2351a86a60'
down_revision: Union[str, Sequence[str], None] = '4dcc379ea8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_name'), table_name='menus')
    op.create_index(op.f('ix_menus_name'), 'menus', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_name'), table_name='menus')
    op.create_index(op.f('ix_menus_name'), 'menus', ['name'], unique=True)
    # ### end Alembic commands ###
