"""Add image column to producto variante

Revision ID: ab2f33ef7a3b
Revises: 4778d2837f93
Create Date: 2025-09-02 17:36:54.709848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2f33ef7a3b'
down_revision: Union[str, Sequence[str], None] = '4778d2837f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto_variantes', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto_variantes', 'image')
    # ### end Alembic commands ###
