"""init 3

Revision ID: d5e66783d46c
Revises: b28cbd213fd6
Create Date: 2025-08-08 22:28:21.907396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e66783d46c'
down_revision: Union[str, Sequence[str], None] = 'b28cbd213fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locales', sa.Column('image', sa.String(), nullable=True))
    op.alter_column('producto_variantes', 'zona_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('producto_variantes', 'zona_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('locales', 'image')
    # ### end Alembic commands ###
