"""init 4

Revision ID: f240cde977d5
Revises: d5e66783d46c
Create Date: 2025-08-13 12:04:52.475869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f240cde977d5'
down_revision: Union[str, Sequence[str], None] = 'd5e66783d46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sucursal_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'users', 'sucursales', ['sucursal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'sucursal_id')
    # ### end Alembic commands ###
